# Datos tabulares con `numpy` e introducción a bucles

In [3]:
#Importamos numpy
import numpy as np

## Introducción a datos tabulares con `numpy`
Recordemos cómo hacer una lista simple en `Python`

In [6]:
#Creamos una lista con caracteres
nombres = ['Denisse', 'Ana', 'Alonso']
#Llamamos al segunda elemento de la lista (índice 1)
nombres[1]

'Ana'

Creamos un array de numpy con la función `numpy.array` y damos una lista como parámetro.

In [8]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

Recuerda que podemos también usar una lista previamente asignada a una variable. Abajo usamos la variable `nombres` para crear un array de `numpy`.

In [10]:
#Utilizamos la misma función
nombres_np = np.array(nombres)

#Imprimimos los resultados
nombres_np

array(['Denisse', 'Ana', 'Alonso'], dtype='<U7')

Tal como lo hicimos con listas, podemos utilizar índices para acceder a los elementos de un array de `numpy`.

In [11]:
nombres_np[2]

'Alonso'

Podemos crear un array de dos dimensiones, utilizando una lista de listas tal como se muestra abajo.

In [29]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

Así como mostramos más arriba, podemos definir varias listas y luego utilizarlas para crear un array de `numpy`.

In [13]:
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]

De hecho, podemos utilizar una combinación de listas previamente asignadas a variables, así como listas directamente en la función `numpy.array`.

In [33]:
np.array([lista1, lista2, [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Recordemos que podemos revisar el tipo de datos en una variable usando la función `type`.

In [5]:
type(arr_2d)

numpy.ndarray

Pero para revisar el tipo de datos dentro de un array de `numpy`, debemos usar el atributo `dtype`.

In [6]:
arr_2d.dtype

dtype('int32')

Podemos revisar el número de dimensiones de un array de `numpy` usando el atributo `ndim`.

In [37]:
arr_2d.ndim

2

Mientras que el atributo `shape` nos permite revisar el número de elementos en cada dimensión.

In [38]:
arr_2d.shape

(2, 3)

Por cierto, un array de `numpy` puede tener más de una o dos dimensiones. Abajo tenemos un array de `numpy` de tres dimensiones.

In [7]:
nuevo_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
nuevo_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Ahora revisemos el número de elementos en cada dimensión.

In [42]:
nuevo_array.shape

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Operaciones matemáticas con arrays de numpy
Vamos a definir dos arrays de `numpy` con números enteros.

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

Podemos llevar a cabo una semana de cada uno de los elementos de los arrays de `numpy` usando el operador `+`.

In [47]:
arr1 + arr2

array([5, 7, 9])

Esto es diferente al resultado que obtenemos al sumar dos listas. En este caso, el operador `+` concatena las dos listas.

In [48]:
[1, 2, 3]+[4, 5, 6]

[1, 2, 3, 4, 5, 6]

Esto significa que no podemos usar el operador `+` para concatenar dos arrays de `numpy` que no contienen el mismo tipo de datos.

In [13]:
nombres = np.array(['Denisse', 'Ana', 'Alonso'])
nombres

array(['Denisse', 'Ana', 'Alonso'], dtype='<U7')

No podemos concatenar el `arr1` y `nombres` porque `arr1` contiene números enteros y `nombres` contiene cadenas de caracteres.

In [14]:
nombres + arr1

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U7'), dtype('int32')) -> None

Esto sólo es posible si utilizamos listas en lugar de arrays de `numpy`.

In [57]:
['Denisse', 'Ana', 'Alonso'] + [1, 2, 3]

['Denisse', 'Ana', 'Alonso', 1, 2, 3]

Tampoco podemos hacer operaciones con arrays de `numpy` que no tienen el mismo número de elementos.

In [15]:
arr1 + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Una multiplicación funciona de la misma manera que una suma. El operador `*` multiplica cada elemento de los arrays de `numpy`. Recuerda que no podemos multiplicar dos arrays de `numpy` que no tienen el mismo número de elementos.

In [49]:
arr1 * arr2

array([ 4, 10, 18])

Pero, sí podemos multiplicar todos los elementos de un array de `numpy` por un solo número.

In [50]:
arr1 * 10

array([10, 20, 30])

Recuerda que todos los elementos de un array de `numpy` deben ser del mismo tipo de datos. Por lo tanto, si intentamos crear un array de `numpy` con elementos de diferentes tipos de datos, `numpy` los convertirá a un solo tipo de datos.

In [22]:
np_mixto = np.array(['Denisse', 'Ana', 2])
np_mixto

array(['Denisse', 'Ana', '2'], dtype='<U11')

In [25]:
np_mixto.dtype

dtype('<U11')

Esto es diferente a lo que sucede con las listas. En este caso, `Python` **no** convierte los elementos a un solo tipo de datos.

In [18]:
lista_mixta = ['Denisse', 'Ana', 2]
lista_mixta

['Denisse', 'Ana', 2]

In [19]:
print(type(lista_mixta[0]), type(lista_mixta[2]))

<class 'str'> <class 'int'>


Es posible usar `np.nan` para representar un valor faltante en un array de `numpy`. Por ejemplo, podemos crear un array de `numpy` con un valor faltante.

In [73]:
np.array([2, 3, 4, np.nan, 5])

array([ 2.,  3.,  4., nan,  5.])

Recuerda que si utilizamos caracteres para representar un valor faltante, `Python` no podrá realizar operaciones matemáticas con el array de `numpy`. Esto es porque convertirá todos los elementos a cadenas de caracteres.

In [26]:
np.array([2, 3, 4, 'NA', 5])

array(['2', '3', '4', 'NA', '5'], dtype='<U11')

Recuerda que también podemos usar índices para seleccionar datos de un array de `numpy`. Si tiene dos dimensiones, podemos usar dos índices separados por una coma. Abajo se muestra cómo seleccionar el primer elemento de la primera fila.	

In [30]:
arr_2d[0, 0]

1

Podemos utilizar esta información dentro de un `f-string` para imprimir el valor del array junto a una oración. Por ejemplo, podemos imprimir el valor del último elemento de la primera fila.

In [31]:
f'El último elemento de mi primera fila es {arr_2d[0, -1]}'

'El último elemento de mi primera fila es 3'

Verifiquemos si esto es correcto.

In [32]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

Podemos también definir un rango de índices para seleccionar varios elementos de un array de `numpy` usando el operador `:`. Abajo seleccionamos los dos elementos de la segunda columna. Nota que si usamos solamente un `:` seleccionamos todos los elementos de esa dimensión.

In [33]:
arr_2d[:, 1]

array([2, 5])

## Utilizando condiciones para seleccionar elementos de un array de numpy

In [27]:
#Definamos un array
nuevo_array = np.array([2, 3, 4, np.nan, 5])
nuevo_array

array([ 2.,  3.,  4., nan,  5.])

Podemos dar una condición entre corchetes (`[]`) para seleccionar elementos de un array de `numpy` que cumplan con esa condición. Por ejemplo, si queremos encontrar los elementos del array de `numpy` que son iguales a 4, podemos hacer lo siguiente.

In [79]:
nuevo_array[nuevo_array == 4]

array([4.])

Podemos dar varias condiciones para seleccionar elementos de un array de `numpy`. Cada condición debe estar dentro de un paréntesis y debemos usar los operadores `&` y `|` para indicar que queremos que se cumplan las condiciones que estamos dando entre los corchetes. Por ejemplo, si queremos encontrar los elementos del array de `numpy` que son igual a 4 o igual a 3, podemos hacer lo siguiente.

In [86]:
nuevo_array[(nuevo_array == 4) | (nuevo_array == 3)]

array([3., 4.])

Esta es la mejor opción cuando queremos extraer rangos de variables, por ejemplo, elementos que sean mayores a 2 pero menores a 5.

In [88]:
nuevo_array[(nuevo_array < 5) & (nuevo_array > 2)]

array([3., 4.])

## Leyendo datos tabulares con numpy desde un archivo
Para leer archivos de texto tipo `csv` o `txt` podemos utilizar la función `numpy.loadtxt`. Esta función tiene varios parámetros, pero los más importantes son `fname` que es el nombre del archivo que queremos leer y `delimiter` que es el delimitador que separa los datos en el archivo. Por ejemplo, si queremos leer el archivo `prueba.csv` que contiene datos en formato `csv`, podemos hacer lo siguiente.

In [43]:
array = np.loadtxt('prueba.csv', delimiter = ',')
array

array([[11.,  0., 19.,  8., 10.,  5.,  6.,  5.,  1.],
       [ 9., 17.,  1., 13., 10., 20., 15., 10., 19.],
       [14.,  4., 17., 13.,  4., 20., 19.,  4., 17.],
       [ 8.,  8., 16.,  9., 10., 20., 12.,  1., 19.],
       [13., 11., 20.,  1., 14.,  9., 12., 16.,  1.],
       [ 2.,  5., 20.,  5., 14.,  8., 11., 15.,  1.],
       [19., 14., 17., 12., 10., 10., 19., 18., 10.],
       [13., 10., 14., 13.,  7., 14.,  4.,  2., 14.],
       [10.,  6., 17.,  1.,  0.,  3., 16., 16.,  8.],
       [15., 11., 16., 16., 14., 17., 17., 12.,  3.],
       [12., 15., 16.,  3.,  9., 12., 15.,  3., 20.],
       [17., 18.,  4.,  6.,  3., 14., 18., 16., 17.],
       [ 2.,  3., 11.,  0.,  5., 20., 16.,  4.,  8.],
       [16.,  7., 13., 20., 10.,  1.,  8., 17.,  1.],
       [ 6., 18.,  8., 15., 14.,  4.,  7., 11.,  2.],
       [ 0.,  6.,  7., 20.,  9.,  9.,  4., 14., 13.],
       [18.,  7.,  7., 18., 16.,  0.,  4., 16., 10.],
       [18., 10., 13.,  2.,  1., 11., 18.,  1.,  9.]])

Ahora podemos hacer operaciones matemáticas con los datos que acabamos de leer.

In [3]:
array = array*2
array

array([[22.,  0., 38., 16., 20., 10., 12., 10.,  2.],
       [18., 34.,  2., 26., 20., 40., 30., 20., 38.],
       [28.,  8., 34., 26.,  8., 40., 38.,  8., 34.],
       [16., 16., 32., 18., 20., 40., 24.,  2., 38.],
       [26., 22., 40.,  2., 28., 18., 24., 32.,  2.],
       [ 4., 10., 40., 10., 28., 16., 22., 30.,  2.],
       [38., 28., 34., 24., 20., 20., 38., 36., 20.],
       [26., 20., 28., 26., 14., 28.,  8.,  4., 28.],
       [20., 12., 34.,  2.,  0.,  6., 32., 32., 16.],
       [30., 22., 32., 32., 28., 34., 34., 24.,  6.],
       [24., 30., 32.,  6., 18., 24., 30.,  6., 40.],
       [34., 36.,  8., 12.,  6., 28., 36., 32., 34.],
       [ 4.,  6., 22.,  0., 10., 40., 32.,  8., 16.],
       [32., 14., 26., 40., 20.,  2., 16., 34.,  2.],
       [12., 36., 16., 30., 28.,  8., 14., 22.,  4.],
       [ 0., 12., 14., 40., 18., 18.,  8., 28., 26.],
       [36., 14., 14., 36., 32.,  0.,  8., 32., 20.],
       [36., 20., 26.,  4.,  2., 22., 36.,  2., 18.]])

Además podemos guardar el resultado usando la función `numpy.savetxt`. Esta función tiene varios parámetros, pero los más importantes son `fname` que es el nombre del archivo que queremos guardar y `delimiter` que es el delimitador que queremos usar para separar los datos en el archivo. Por ejemplo, si queremos guardar el resultado de la operación matemática que acabamos de hacer en un archivo `csv`, podemos hacer lo siguiente.

In [4]:
np.savetxt('prueba3.csv', array, delimiter = ',')

No es posible guardar un array de `numpy` como un archivo de excel directamente. Pero podemos transformar un array de `numpy` a un dataframe de `pandas` y luego guardar el dataframe como un archivo de excel. Para hacer esto, primero debemos importar la librería `pandas` y luego usar la función `pandas.DataFrame` para crear un dataframe de `pandas` a partir del array de `numpy`. Luego guardamos el dataframe como un archivo de excel usando la función `pandas.to_excel`. 

In [5]:
import pandas as pd

Creamos un dataframe de `pandas` a partir del array de `numpy`.

In [8]:
df = pd.DataFrame(array)
df

0     1     2     3     4     5     6     7     8
0   22.0   0.0  38.0  16.0  20.0  10.0  12.0  10.0   2.0
1   18.0  34.0   2.0  26.0  20.0  40.0  30.0  20.0  38.0
2   28.0   8.0  34.0  26.0   8.0  40.0  38.0   8.0  34.0
3   16.0  16.0  32.0  18.0  20.0  40.0  24.0   2.0  38.0
4   26.0  22.0  40.0   2.0  28.0  18.0  24.0  32.0   2.0
5    4.0  10.0  40.0  10.0  28.0  16.0  22.0  30.0   2.0
6   38.0  28.0  34.0  24.0  20.0  20.0  38.0  36.0  20.0
7   26.0  20.0  28.0  26.0  14.0  28.0   8.0   4.0  28.0
8   20.0  12.0  34.0   2.0   0.0   6.0  32.0  32.0  16.0
9   30.0  22.0  32.0  32.0  28.0  34.0  34.0  24.0   6.0
10  24.0  30.0  32.0   6.0  18.0  24.0  30.0   6.0  40.0
11  34.0  36.0   8.0  12.0   6.0  28.0  36.0  32.0  34.0
12   4.0   6.0  22.0   0.0  10.0  40.0  32.0   8.0  16.0
13  32.0  14.0  26.0  40.0  20.0   2.0  16.0  34.0   2.0
14  12.0  36.0  16.0  30.0  28.0   8.0  14.0  22.0   4.0
15   0.0  12.0  14.0  40.0  18.0  18.0   8.0  28.0  26.0
16  36.0  14.0  14.0  36.0  32.0   0.0   8.0  32.0  20.0
17  36.0  20.0  26.0   4.0   2.0  22.0  36.0   2.0  18.0

Ahora guardamos el resultado como archivo de excel usando la función `pandas.to_excel`.

In [11]:
df.to_excel('prueba.xlsx')

Si queremos cambiar el valor de los elementos de un array que cumplan cierta condición podemos seleccionarlo usando condiciones tal como vimos más arriba. Por ejemplo, si queremos cambiar todos los elementos del array que sean menores a 5 pero mayores a 0 a valores faltantes, podemos:  
- Definir la condición que queremos que cumplan los elementos que queremos cambiar.  
- Seleccionar los elementos que cumplan con la condición.
- Cambiar los elementos seleccionados a `np.nan`.

In [45]:
array[(array > 0) & (array < 5)]

array([1., 1., 4., 4., 4., 1., 1., 1., 2., 1., 4., 2., 1., 3., 3., 3., 3.,
       4., 3., 2., 3., 4., 1., 1., 4., 2., 4., 4., 2., 1., 1.])

Si queremos aplicar varias funciones a esta selección de números podemos guardar la máscara producida al aplicar cierta condición.

In [51]:
(array > 0) & (array < 5)

array([[False, False, False, False, False, False, False, False,  True],
       [False, False,  True, False, False, False, False, False, False],
       [False,  True, False, False,  True, False, False,  True, False],
       [False, False, False, False, False, False, False,  True, False],
       [False, False, False,  True, False, False, False, False,  True],
       [ True, False, False, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True,  True, False],
       [False, False, False,  True, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False,  True],
       [False, False, False,  True, False, False, False,  True, False],
       [False, False,  True, False,  True, False, False, False, False],
       [ True,  True, False, False, False, False, False,  True, False],
       [False, False, False, False, False,  True, False, False, 

Esto nos da una serie de booleanos que podemos guardar en una variable para asignarlos a un array de `numpy`.

In [52]:
mascara = (array > 0) & (array < 5)

Ahora aplicamos esta máscara al array original y nos dará el mismo resultado que cuando aplicamos la condición directamente al array.

In [53]:
array[mascara]

array([1., 1., 4., 4., 4., 1., 1., 1., 2., 1., 4., 2., 1., 3., 3., 3., 3.,
       4., 3., 2., 3., 4., 1., 1., 4., 2., 4., 4., 2., 1., 1.])

Podemos verificar que los resultados son los mismos de la siguiente manera.

In [54]:
array[(array > 0) & (array < 5)] == array[mascara]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

Usando cualquiera de los dos métodos podemos ahora cambiar los elementos seleccionados a `np.nan`.

In [55]:
array[mascara] = np.nan

Ahora verificamos los resultados.

In [56]:
array

array([[11.,  0., 19.,  8., 10.,  5.,  6.,  5., nan],
       [ 9., 17., nan, 13., 10., 20., 15., 10., 19.],
       [14., nan, 17., 13., nan, 20., 19., nan, 17.],
       [ 8.,  8., 16.,  9., 10., 20., 12., nan, 19.],
       [13., 11., 20., nan, 14.,  9., 12., 16., nan],
       [nan,  5., 20.,  5., 14.,  8., 11., 15., nan],
       [19., 14., 17., 12., 10., 10., 19., 18., 10.],
       [13., 10., 14., 13.,  7., 14., nan, nan, 14.],
       [10.,  6., 17., nan,  0., nan, 16., 16.,  8.],
       [15., 11., 16., 16., 14., 17., 17., 12., nan],
       [12., 15., 16., nan,  9., 12., 15., nan, 20.],
       [17., 18., nan,  6., nan, 14., 18., 16., 17.],
       [nan, nan, 11.,  0.,  5., 20., 16., nan,  8.],
       [16.,  7., 13., 20., 10., nan,  8., 17., nan],
       [ 6., 18.,  8., 15., 14., nan,  7., 11., nan],
       [ 0.,  6.,  7., 20.,  9.,  9., nan, 14., 13.],
       [18.,  7.,  7., 18., 16.,  0., nan, 16., 10.],
       [18., 10., 13., nan, nan, 11., 18., nan,  9.]])

Podemos también acceder a archivos de texto disponibles en internet usando la misma función de `numpy.loadtxt`. Por ejemplo, si queremos leer el archivo `prueba.csv` que está disponible en nuestro repositorio.  
  
El arhivo en nuestro repositorio incluye caracteres, por lo que si queremos acceder a todos los elementos en esta tabla, debemos especificar que el tipo de datos es una cadena de caracteres. Para hacer esto, podemos usar el parámetro `dtype` y darle el valor `str`.

In [35]:
prueba = np.loadtxt('https://raw.githubusercontent.com/laboratoriolide/new-dimensions/main/Python/prueba2.csv',
 delimiter = ',',  dtype = 'str')
prueba

array([['\ufeffNombre', 'Edad', 'Peso_kg', 'Altura_m'],
       ['Ana', '33', '60', '1.6'],
       ['Manuel', '38', '80', '1.82'],
       ['Daniela', '29', '70', '1.54'],
       ['Jose', '25', '100', '1.7'],
       ['Sara', '40', '95', '1.75']], dtype='<U8')

Recuerda que el URL que usamos arriba lo obtuvimos al presionar la opción `Raw` en el archivo `prueba.csv` en nuestro repositorio.  
  
Si queremos ignorar la primera fila de este archivo que contiene los nombres de las columnas, podemos utilizar el parámetro `skiprows` y darle el valor `1`. Esto quiere decir que vamos a ignorar la primera file en este archivo. Nota que aún debemos especificar el parámetro `dtype` para que `numpy` sepa que todos los elementos en este archivo son cadenas de caracteres, ya que la primera columna contiene caracteres.

In [17]:
np.loadtxt('https://raw.githubusercontent.com/laboratoriolide/new-dimensions/main/Python/prueba2.csv',
 delimiter = ',', skiprows = 1, dtype = 'str')

array([['Ana', '33', '60', '1.6'],
       ['Manuel', '38', '80', '1.82'],
       ['Daniela', '29', '70', '1.54'],
       ['Jose', '25', '100', '1.7'],
       ['Sara', '40', '95', '1.75']], dtype='<U7')

Si queremos guardar los nombres de la columnas (primera fila) y los datos de la primera columna (`Nombre`), podemos hacer lo siguiente.

In [37]:
columnas = prueba[0, :]
nombres = prueba[1:, 0]
print(columnas, nombres)

['\ufeffNombre' 'Edad' 'Peso_kg' 'Altura_m'] ['Ana' 'Manuel' 'Daniela' 'Jose' 'Sara']


Si solo queremos mantener los números en nuestro archivo, podemos no solo ignorar filas que contienen caracteres, sino también escoger las columnas que contienen números. Para hacer esto, podemos usar el parámetro `usecols` y darle una lista con los índices de las columnas que queremos mantener. Por ejemplo, si queremos mantener las columnas 1, 2 y 3, podemos hacer lo siguiente. 

In [38]:
datos = np.loadtxt('https://raw.githubusercontent.com/laboratoriolide/new-dimensions/main/Python/prueba2.csv',
 delimiter = ',', skiprows = 1, usecols = [1, 2, 3])
datos

array([[ 33.  ,  60.  ,   1.6 ],
       [ 38.  ,  80.  ,   1.82],
       [ 29.  ,  70.  ,   1.54],
       [ 25.  , 100.  ,   1.7 ],
       [ 40.  ,  95.  ,   1.75]])

Nota que no podemos utilizar rangos en el parámetro `usecols` porque esto resultará en un error.

In [39]:
np.loadtxt('https://raw.githubusercontent.com/laboratoriolide/new-dimensions/main/Python/prueba2.csv',
 delimiter = ',', skiprows = 1, usecols = [1:3])

SyntaxError: invalid syntax (1321252751.py, line 2)

## Funciones matemáticas con arrays de `numpy`
El paquete `numpy` incluye varias funciones matemáticas que podemos utilizar con arrays de `numpy`. Por ejemplo, podemos calcular el promedio de todos los elementos en un array de `numpy` usando la función `numpy.mean`.

In [42]:
np.mean(datos[:,0])

33.0

Nota que esto calculará el promedio de todos los elementos en el array de `numpy`. También podemos sumar elementos de una array de `numpy` usando la función `numpy.sum`.

In [40]:
np.sum(datos[:,0])

165.0

En este caso, la función `numpy.sum` suma todos los elementos de la primera columna en el array de `numpy`.  
  
Podemos también calcular la desviación estándar de los elementos de la primera fila usando la función `numpy.std`.

In [41]:
np.std(datos[0, :])

23.864245687266596

Podemos también definir un rango de valores usando la función `numpy.arange`. Esta función tiene varios parámetros, pero los más importantes son `start` que es el valor inicial del rango, `stop` que es el valor final del rango y `step` que es el tamaño del paso entre los valores en el rango. Por ejemplo, si queremos crear un rango de valores de 0 a 10 con un paso de 2, podemos hacer lo siguiente.

In [58]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

Recuerda que el valor final del rango no está incluido. Por lo tanto, si queremos incluir el valor final del rango, debemos sumar 1 al valor final.  

## Introducción a bucles
Podemos usar estos rangos para calcular promedios por cada columna en un array de `numpy`. Abajo definimos un bucle `for` que itera sobre los índices de las columnas en el array de `numpy`. Recordemos que podemos ver los elementos de cada dimensión de un array con shape.

In [61]:
datos.shape

(5, 3)

El primer valor se refiere a las filas, mientras que el segundo se refiere a las columnas. Si queremos utilizar el número de columnas, entonces debemos utilizar el índice 1.

In [63]:
datos.shape[1]

3

Ahora utilizamos esta información para definir un rango de valores que incluye todos los índices de las columnas en el array de `numpy`.

In [64]:
np.arange(0, datos.shape[1])

array([0, 1, 2])

Esto se convertirá en nuestro índice en el bucle `for`. Este índice deberá ser pasado como el segundo índice (que se refiere a las columnas) para calcular los promedios.

In [65]:
for col in np.arange(0, datos.shape[1]):
      print(np.mean(datos[:, col]))

33.0
81.0
1.682


Sin embargo, esto lo podemos hacer de manera mucho más rápida utilizando la función `numpy.mean` y el parámetro `axis`. Este parámetro nos permite calcular el promedio por cada fila (`axis = 1`) o por cada columna (`axis = 0`). Por ejemplo, si queremos calcular el promedio por cada columna, podemos hacer lo siguiente.

In [66]:
np.mean(datos, axis = 0)

array([33.   , 81.   ,  1.682])

Como puedes ver, el resultado es el mismo que cuando utilizamos un bucle `for`.  

Podemos calcular el promedio por fila de la misma manera, sea utilizando un bucle `for` o utilizando el parámetro `axis` en la función `numpy.mean`.

In [67]:
#Con bucle
for row in np.arange(0, datos.shape[0]):
      print(np.mean(datos[row,:]))

31.53333333333333
39.94
33.513333333333335
42.233333333333334
45.583333333333336


In [68]:
#Directamente en numpy utilizando axis = 1
np.mean(datos, axis = 1)

array([31.53333333, 39.94      , 33.51333333, 42.23333333, 45.58333333])